In [24]:
a = (1,2,3)
b = (4,5,6)

In [25]:
print(a)
type(a)

(1, 2, 3)


tuple

In [26]:
a+b

(1, 2, 3, 4, 5, 6)

In [8]:
a-b

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [44]:
c = [1,2,3]
d = [4,5,6]

In [45]:
print(c)
type(c)

[1, 2, 3]


list

In [46]:
c+d

[1, 2, 3, 4, 5, 6]

In [47]:
c*d

TypeError: can't multiply sequence by non-int of type 'list'

In [43]:
import numpy as np
c = np.array(c)
d = np.array(d)

print(type(c))

print(c+d)
print(c-d)
print(c*d)
print(c/d)


<class 'numpy.ndarray'>
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
